{
"project": { "Code":"sp", "Name":"Приобретение программы","Version":"1","CurTime":1169010000,"Notes":"Тестовый проект" },
"parameters": { "language":"ru", "dateFormat":"", "dateDelim":".", "timeDelim":":", "secondsInPixel":30000, "expandToLevelAtStart":3, "uploadTime":1603123121 },
"activities": [
 {"Level":1,"Code":"main","N":"65408","Name":"Приобретение программы","Person":null,"Notes":null,"Start":1168318800,"AsapStart":1169010000,"AsapFin":1176103800,"FactStart":1168318800,"FactFin":null,"f_FontColor":null,"f_LastFin":1168952400,"f_ColorCom":"11534336","f_ColorBack":"13233656"},
 {"Level":2,"Code":"Груша","N":"65408","Name":"Требования и рынок","Person":"ivanov, petrov","Notes":null,"Start":1168318800,"AsapStart":1169010000,"AsapFin":1173801600,"FactStart":1168318800,"FactFin":null,"f_FontColor":"255","f_LastFin":1168952400,"f_ColorCom":"53760","f_ColorBack":"13434828"}
],
"table": [
{"name":"Уровень","ref":"Level","visible":true,"width":2,"type":"int", "format":0},
{"name":"Код","ref":"Code","visible":true,"width":17,"type":"string", "format":2},
{"name":"Пользовательское поле N","ref":"N","visible":true,"width":17,"type":"signal", "format":1},
{"name":"Название","ref":"Name","visible":true,"width":40,"type":"string", "format":0},
{"name":"Менеджер","ref":"Person","visible":true,"width":17,"type":"string", "format":0},
{"name":"Комментарии","ref":"Notes","visible":true,"width":17,"type":"text", "format":0, "editable":true},
{"name":"Начало","ref":"Start","visible":true,"width":17,"type":"datetime", "format":1}
],
"links": [
 {"PredCode":"spamrd01","SuccCode":"spamrd04","TypeSF2":"FS"},
 {"PredCode":"spamrd02","SuccCode":"spamrd04","TypeSF2":"FS"},
 {"PredCode":"spamrd04","SuccCode":"spammr03","TypeSF2":"FS"},
 {"PredCode":"spscsa03","SuccCode":"spscsa04","TypeSF2":"FS"},
 {"PredCode":"spscsa04","SuccCode":"spscic01","TypeSF2":"FS"},
 {"PredCode":"spscsa04","SuccCode":"spscic02","TypeSF2":"FS"},
 {"PredCode":"spscnc01","SuccCode":"spscnc02","TypeSF2":"FS"},
 {"PredCode":"spscnc02","SuccCode":"spscnc03","TypeSF2":"FS"},
 {"PredCode":"spammr03","SuccCode":"spscsa01","TypeSF2":"FS"},
 {"PredCode":"spscsa01","SuccCode":"spscsa02","TypeSF2":"FS"},
 {"PredCode":"spscsa01","SuccCode":"spscsa03","TypeSF2":"FS"},
 {"PredCode":"spscic02","SuccCode":"spscnc01","TypeSF2":"FS"},
 {"PredCode":"spscic01","SuccCode":"spscnc01","TypeSF2":"FS"},
 {"PredCode":"spamrd03","SuccCode":"spamrd04","TypeSF2":"FS"},
 {"PredCode":"spamrd01","SuccCode":"spamrd03","TypeSF2":"FS"},
 {"PredCode":"spamrd02","SuccCode":"spamrd03","TypeSF2":"FS"},
 {"PredCode":"spammr01","SuccCode":"spammr02","TypeSF2":"FS"},
 {"PredCode":"spammr02","SuccCode":"spammr03","TypeSF2":"FS"},
 {"PredCode":"spscsa02","SuccCode":"spscsa05","TypeSF2":"FS"},
 {"PredCode":"spscsa05","SuccCode":"spscsa04","TypeSF2":"FS"},
 {"PredCode":"spamrd01","SuccCode":"ww","TypeSF2":"SS"},
 {"PredCode":"spammr03","SuccCode":"ww","TypeSF2":"FF"},
 {"PredCode":"spscsa01","SuccCode":"spsc01","TypeSF2":"FS"},
 {"PredCode":"spscnc03","SuccCode":"spsc01","TypeSF2":"FF"},
 {"PredCode":"spamrd02","SuccCode":"ww","TypeSF2":"SS"},
 {"PredCode":"spamrd01","SuccCode":"spscnc03","TypeSF2":"FS"},
 {"PredCode":"spamrd02","SuccCode":"spscnc03","TypeSF2":"FS"},
 {"PredCode":"spamrd01","SuccCode":"spammr01","TypeSF2":"FS"},
 {"PredCode":"spamrd01","SuccCode":"spammr01","TypeSF2":"FS"},
 {"PredCode":"spamrd01","SuccCode":"spammr01","TypeSF2":"FF"},
 {"PredCode":"spamrd01","SuccCode":"spammr01","TypeSF2":"FS"},
 {"PredCode":"spamrd01","SuccCode":"03","TypeSF2":"SS"},
 {"PredCode":"spammr03","SuccCode":"03","TypeSF2":"FF"},
 {"PredCode":"spamrd02","SuccCode":"03","TypeSF2":"SS"}
],
"lang":"ru"
}